//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quill.WebApi.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public string CustomerIdentity { get; set; }
        public string Password { get; set; }
        public string CellPhone { get; set; }
        public string CustomerName { get; set; }
        public string IdCardNo { get; set; }
        public string MemberCardNo { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public int CreditLevel { get; set; }
        public int OrderCount { get; set; }
    }
}
